import {beforeEach,describe,expect,it,vi} from 'vitest';
vi.hoisted(()=>{Object.defineProperty(globalThis,'matchMedia',{value:()=>({matches:true}),configurable:true});});
const transport=vi.hoisted(()=>({post:vi.fn()}));
vi.mock('./api',()=>({api:vi.fn(),post:transport.post,ApiError:class ApiError extends Error {constructor(message:string,public status:number){super(message);}}}));
vi.mock('./drafts',()=>({persistDraft:vi.fn(async()=>{}),recoverDraft:vi.fn(async()=>undefined),archiveDraft:vi.fn(async()=>{}),updateArchivedHead:vi.fn(async()=>{})}));
import {EXAMPLES,cloneScene,newId} from '../../../packages/core/src';
import {useEditor,setGeometryValidation} from './store';
import {ApiError} from './api';
beforeEach(()=>{transport.post.mockReset();setGeometryValidation(null);useEditor.setState({scene:cloneScene(EXAMPLES[0].scene),selected:['gravity-headline'],past:[],future:[],gesture:null,mutationEpoch:0,requestGeneration:0,affected:[],documentId:newId(),projectId:null,serverHead:null,outbox:[],playing:false,recording:false});});
describe('editor revision and AI races',()=>{
 it('keeps the last good revision when font geometry validation fails for manual, AI or gesture changes',()=>{const before=useEditor.getState().scene;setGeometryValidation(()=>{throw new Error('Layer does not fit the artboard');});expect(useEditor.getState().commit(s=>{s.layers[0].layout.x=16;})).toBe(false);expect(useEditor.getState().scene).toBe(before);const capture=useEditor.getState().beginAi();expect(()=>useEditor.getState().applyAi(capture,[{type:'setLayout',layerId:'gravity-headline',changes:{x:16}}],false)).toThrow('does not fit');expect(useEditor.getState().scene).toBe(before);useEditor.getState().beginGesture();useEditor.getState().moveGesture(-500,0);useEditor.getState().endGesture();expect(useEditor.getState().scene).toEqual(before);expect(useEditor.getState().past).toHaveLength(0);});
 it('undo restores content with a fresh revision and rejects an old AI reply',()=>{const initial=cloneScene(useEditor.getState().scene);const capture=useEditor.getState().beginAi();useEditor.getState().commit(s=>{s.layers.find(l=>l.id==='gravity-headline')!.layout.x+=10;});useEditor.getState().undo();const restored=useEditor.getState().scene;expect(restored.layers).toEqual(initial.layers);expect(restored.revision.id).not.toBe(initial.revision.id);expect(useEditor.getState().applyAi(capture,[{type:'setFill',layerId:'gravity-headline',colour:'#ff0000'}],false)).toBe(false);expect(useEditor.getState().scene).toBe(restored);});
 it('a gesture invalidates responses even when it is cancelled without a history item',()=>{const capture=useEditor.getState().beginAi();const initial=cloneScene(useEditor.getState().scene);useEditor.getState().beginGesture();useEditor.getState().moveGesture(20,30);expect(useEditor.getState().applyAi(capture,[],false)).toBe(false);useEditor.getState().endGesture(true);expect(useEditor.getState().scene).toEqual(initial);expect(useEditor.getState().past).toHaveLength(0);expect(useEditor.getState().applyAi(capture,[],false)).toBe(false);});
 it('commits an entire drag as one history item using base coordinates',()=>{const initial=cloneScene(useEditor.getState().scene);useEditor.getState().beginGesture();useEditor.getState().moveGesture(10,20);useEditor.getState().moveGesture(20,30);useEditor.getState().endGesture();expect(useEditor.getState().past).toHaveLength(1);expect(useEditor.getState().scene.layers.find(l=>l.id==='gravity-headline')!.layout.x).toBe(initial.layers.find(l=>l.id==='gravity-headline')!.layout.x+20);useEditor.getState().undo();expect(useEditor.getState().scene.layers).toEqual(initial.layers);useEditor.getState().redo();expect(useEditor.getState().past).toHaveLength(1);});
 it('cleans references when deleting an anchor and restores them together',()=>{useEditor.getState().removeSelected();expect(useEditor.getState().scene.layers.flatMap(l=>l.behaviors).filter(b=>b.type==='attract')).toHaveLength(0);useEditor.getState().undo();expect(useEditor.getState().scene.layers.flatMap(l=>l.behaviors).filter(b=>b.type==='attract')).toHaveLength(4);});
 it('rejects responses after switching documents or submitting a newer request',()=>{const capture=useEditor.getState().beginAi();useEditor.getState().beginAi();expect(useEditor.getState().applyAi(capture,[],false)).toBe(false);const next=useEditor.getState().beginAi();useEditor.getState().replace(EXAMPLES[1].scene);expect(useEditor.getState().applyAi(next,[],false)).toBe(false);});
});
describe('serialized durable saves',()=>{
 it('preserves a conflicted document while allowing an unrelated draft to save',async()=>{transport.post.mockRejectedValueOnce(new ApiError('Head changed',409));useEditor.setState({projectId:'conflicted-project',serverHead:'previous'});await useEditor.getState().enqueueSave();expect(useEditor.getState().outbox[0].blocked).toBe(true);useEditor.getState().replace(EXAMPLES[1].scene);transport.post.mockResolvedValueOnce({project:{id:'healthy-project',headRevisionId:useEditor.getState().scene.revision.id}});await useEditor.getState().enqueueSave();expect(transport.post).toHaveBeenCalledTimes(2);expect(useEditor.getState().projectId).toBe('healthy-project');expect(useEditor.getState().outbox).toHaveLength(1);expect(useEditor.getState().outbox[0].projectId).toBe('conflicted-project');});
 it('does not drop a new project queued while a removed old project request is in flight',async()=>{let resolve!:(value:unknown)=>void;transport.post.mockImplementationOnce(()=>new Promise(r=>resolve=r));const old=useEditor.getState().enqueueSave();await vi.waitFor(()=>expect(transport.post).toHaveBeenCalledTimes(1));useEditor.setState({documentId:newId(),outbox:[],projectId:null,serverHead:null});transport.post.mockResolvedValueOnce({project:{id:'new-project',headRevisionId:useEditor.getState().scene.revision.id}});await useEditor.getState().enqueueSave();expect(useEditor.getState().outbox).toHaveLength(1);resolve({project:{id:'old-project',headRevisionId:'old'}});await old;expect(transport.post).toHaveBeenCalledTimes(2);expect(useEditor.getState().projectId).toBe('new-project');expect(useEditor.getState().outbox).toHaveLength(0);});
 it('a late save acknowledgement never replaces newer local edits, and the next save follows the acknowledged head',async()=>{let resolve!:(value:unknown)=>void;transport.post.mockImplementationOnce(()=>new Promise(r=>resolve=r));const savedRevision=useEditor.getState().scene.revision.id;const saving=useEditor.getState().enqueueSave();await vi.waitFor(()=>expect(transport.post).toHaveBeenCalledTimes(1));useEditor.getState().commit(scene=>{scene.layers[0].fill='#123456';});const newest=useEditor.getState().scene;resolve({project:{id:'project-1',name:'Gravity',headRevisionId:savedRevision},scene:EXAMPLES[0].scene});await saving;expect(useEditor.getState().scene).toBe(newest);expect(useEditor.getState().serverHead).toBe(savedRevision);transport.post.mockResolvedValueOnce({headRevisionId:newest.revision.id,revisionId:newest.revision.id});await useEditor.getState().enqueueSave();expect(transport.post.mock.calls[1][1].expectedHeadRevisionId).toBe(savedRevision);expect(useEditor.getState().outbox).toHaveLength(0);});
 it('a late acknowledgement for a previous document does not attach the open draft to that project',async()=>{let resolve!:(value:unknown)=>void;transport.post.mockImplementationOnce(()=>new Promise(r=>resolve=r));const saving=useEditor.getState().enqueueSave();await vi.waitFor(()=>expect(transport.post).toHaveBeenCalledTimes(1));useEditor.getState().replace(EXAMPLES[1].scene);const newer=useEditor.getState().scene;resolve({project:{id:'old-project',headRevisionId:'old-revision'}});await saving;expect(useEditor.getState().projectId).toBeNull();expect(useEditor.getState().scene).toBe(newer);});
});
